### ISSUE TITLE
Publishing?

### ISSUE THREAD

**Issue by robcresswell** [mgred/quickjs-types#2]
Hello! Thanks for writing this. Any plans to publish it somewhere for a more standard JS workflow, perhaps npm? Git submodules are not typically widely used (at least, anecdotally I've not seen them used much in JS-land)

**Comment by mgred** [comment]
Hey, Rob!

In deed, submodules are not the common way to publish such packages. I have already created an [npm package](https://www.npmjs.com/package/@qjsx/types) for the types from another [repository](https://github.com/mgred/qjsx). However, the last fix #1 from @sax1johno is still missing in this package.
Feel free to use this package and don't hesitate to improve or suggest new features :smile:

**Comment by robcresswell** [comment]
Oh, sorry! My bad. Thankyou!
